- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Kubernetes tools
      apt:
        name:
          - kubectl
          - kubeadm
          - kubelet
        state: present